services:
  db:
    image: postgres:16.1
    container_name: postgres_shareit
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@db:5432/shareit -v ON_ERROR_STOP=1 <<-EOSQL
        DROP TABLE IF EXISTS comments CASCADE;
        DROP TABLE IF EXISTS bookings CASCADE;
        DROP TABLE IF EXISTS item_requests CASCADE;
        DROP TABLE IF EXISTS items CASCADE;
        DROP TABLE IF EXISTS users CASCADE;
        
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          email VARCHAR(512) NOT NULL,
          CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
        );
        
        CREATE TABLE IF NOT EXISTS item_requests (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          description VARCHAR(512) NOT NULL,
          requestor_id BIGINT NOT NULL,
          created TIMESTAMP WITHOUT TIME ZONE,
          CONSTRAINT fk_item_requests_to_users FOREIGN KEY(requestor_id) REFERENCES users(id)
        );
        
        CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          description VARCHAR(2000) NOT NULL,
          is_available BOOLEAN,
          owner_id BIGINT NOT NULL,
          request_id BIGINT,
          CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(id),
          CONSTRAINT fk_items_to_requests FOREIGN KEY(request_id) REFERENCES item_requests(id)
        );
        
        CREATE TABLE IF NOT EXISTS bookings (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          start_date TIMESTAMP WITHOUT TIME ZONE,
          end_date TIMESTAMP WITHOUT TIME ZONE,
          item_id BIGINT NOT NULL,
          booker_id BIGINT NOT NULL,
          status VARCHAR(50),
          CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(id),
          CONSTRAINT fk_bookings_to_users FOREIGN KEY(booker_id) REFERENCES users(id)
        );
        
        CREATE TABLE IF NOT EXISTS comments (
          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          text VARCHAR(1000) NOT NULL,
          item_id BIGINT NOT NULL,
          author_id BIGINT NOT NULL,
          created TIMESTAMP WITHOUT TIME ZONE,
          CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id),
          CONSTRAINT fk_comments_to_users FOREIGN KEY(author_id) REFERENCES users(id)
        );
        EOSQL